language: go
install: true
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
go:
  - 1.19.x
script:
  - go get -v -t -d ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.19